### ISSUE TITLE
Ouija not loading

### ISSUE THREAD

**Issue by jonwgeorge** [ouija-io/ouija#23] opened 2014-05-01 19:14 UTC
I know Ouija is not quite ready for production use, but I like to play with code. I used the quick install guide to get Ouija up and running but it doesn't seem to do anything on my ghost install. I see it connecting in the Javascript Console, but no elements are added to my page.

Did I miss something?

Edit: You can see my blog [here](http://www.jonwgeorge.com).

**Comment by strues** [comment] 2014-05-01 19:17
Same thing here, but I also tried with the developer install. It definitely is trying to work, but like jon said, nothing happens past the initial connect

**Comment by colinmacdonald** [comment] 2014-05-01 19:28
jonwgeorge, it looks like an old build is cached on our CDN. When I open a post on your blog (http://www.jonwgeorge.com/what-is-open-source-and-why-should-you-care/) I see the error from the cached file.

If you append `?v=1` to the end of `http://cdn.goinstant.net/external/ouija/latest/ouija.min.js` you should bypass the cache (`https://cdn.goinstant.net/external/ouija/latest/ouija.min.js?v=1`).

Let me know if that works out for you.

**Comment by colinmacdonald** [comment] 2014-05-01 19:28
strues, this same thing may apply to you as well.

**Comment by strues** [comment] 2014-05-01 19:32
I'll give it a shot using that instead of the file from the repo here. My blog is at https://www.himynameissteve.com/

**Comment by jonwgeorge** [comment] 2014-05-01 19:34
Doesn't look like that solved the problem for me. I wasn't aware my content was cached. I'm on Ghost(Pro) so that probably explains it.

**Comment by jonwgeorge** [comment] 2014-05-01 19:35
As a side note, when I head to my GoInstant dashboard, I'm seeing data being populated back in the form of users for each post.

**Comment by mattcreager** [comment] 2014-05-01 19:37
@colinmacdonald it's possible in @jonwgeorge case that his theme is atypical... It looks like the content on his blog is in a sub-section with class `post-excerpt`.  I wonder if Ouija is just failing to find his content?

**Comment by colinmacdonald** [comment] 2014-05-01 19:38
The themes being used by both jonwgeorge and strues are not supported by Ouija ATM :(.

**Comment by jonwgeorge** [comment] 2014-05-01 19:40
@colinmacdonald @mattcreager Since mine is a custom theme, what modifications should I make to make it compatible? Or can I help in anyway with making Ouija compatible with my type of theme?

**Comment by strues** [comment] 2014-05-01 19:43
I made the switch to Casper and it appears that everything is working as intended now. I'm wondering the same thing as @jonwgeorge I dont mind messing around and breaking a few things on my end as the blog is still being developed

**Comment by mattcreager** [comment] 2014-05-01 19:44
@strues, @jonwgeorge what if we offered a simple configuration option you drop into `config/ouija.json` that provides a specific content destination id? aka: `#my-article-content` ?

**Comment by jonwgeorge** [comment] 2014-05-01 19:47
@mattcreager that could definitely work, at least in my case, it should just be looking for a section tag with the id of 'articles'.

**Comment by jonwgeorge** [comment] 2014-05-01 19:48
@mattcreager that would mean I would have to host those files myself, rather than loading all from your CDN correct?

**Comment by mattcreager** [comment] 2014-05-01 19:49
@jonwgeorge nope, we'll push a fix to the CDN too!

Ouija's first fix, how exciting :)

**Comment by jonwgeorge** [comment] 2014-05-01 19:50
@mattcreager haha! If I can be of any assistance in the process, just let me know. I'm excited to see what ya'll do with Ghost and Ouija.

**Comment by mattcreager** [comment] 2014-05-01 19:52
@jonwgeorge  So far: just break things.

@colinmacdonald is in the process of adding that option override right now.  Long term, we'll need to make finding the content auto-magically more magical.

**Comment by colinmacdonald** [comment] 2014-05-01 19:52
@jonwgeorge is the theme you're using publicly available?

**Comment by jonwgeorge** [comment] 2014-05-01 19:53
@colinmacdonald nope. but give me a few minutes and I'll put it up for you.

**Comment by jonwgeorge** [comment] 2014-05-01 19:56
@colinmacdonald here you go https://github.com/jonwgeorge/ghost-theme

**Comment by colinmacdonald** [comment] 2014-05-01 19:59
Thanks!

**Comment by jonwgeorge** [comment] 2014-05-01 20:46
@colinmacdonald Please let me know when I can test this change.

**Comment by colinmacdonald** [comment] 2014-05-01 21:03
@jonwgeorge You should be able to test out the new `ouija_article_content` option using `v0.1.1`.

Under `window.ouija_identifier` in default.hbs put `window.ouija_article_content = '.post-excerpt';`. 

This will let Ouija know where to put the comment blocks. There will still be some styling kinks that need to worked out (as you will see). @ntassone will be able to give some insight into what's needed there soon.

**Comment by ntassone** [comment] 2014-05-01 21:03
@jonwgeorge since your blog is a custom theme, you'll require some custom css to get Ouija exactly how you want it. I'm working on making a better reset for Ouija that will allow for more consistency across more types of themes. See #22.

I checked out your blog repo and was able to get Ouija working with a few lines of custom CSS I put in `style.css`. Wherever you end up putting the custom CSS just make sure it's after `ouija.css`.  

Custom styles: https://gist.github.com/ntassone/1e16ebaa55e48fb39a30

**Comment by jonwgeorge** [comment] 2014-05-01 21:14
@colinmacdonald So will I need to download <code>v0.1.1</code> or can I pull it from the CDN?

@ntassone thank you!

**Comment by mattcreager** [comment] 2014-05-01 21:15
This is why the world loves @ntassone :+1:

**Comment by colinmacdonald** [comment] 2014-05-01 21:21
@jonwgeorge you can pull it from the cdn, https://cdn.goinstant.net/external/ouija/v0.1.1/ouija.min.js and ouija.min.css

**Comment by jonwgeorge** [comment] 2014-05-01 21:24
Awesome!! You guys are great. Time to start playing around.

**Comment by ntassone** [comment] 2014-05-08 17:41
Going to close this, feel free to reopen if you're still having issues @jonwgeorge

**Closed as completed by ntassone** 2014-05-08 17:41 UTC
